### ISSUE TITLE
Documentation has to be written.

### ISSUE THREAD

**Issue by IIvexII** [IIvexII/LGU-TimetableAPI#15]
### Description 
This project will be hard to maintain or reuse for the contributors because the documentation is not written. Before we go any further, writing documentation must be written to save hard work on this project to go in vain.

### TODO
- [ ]  Update ReadMe.md to create more useful first look of the repository.
- [x] #18
- [ ] Write `src/docs/Examples.md`
- [ ] Document the `GoogleCalendar.js` in `src/lib/GoogleCalendar.js` to show how it works

**Comment by JanitaRiyaz** [comment]
ok..got it..

**Comment by JanitaRiyaz** [comment]
Kindly tell me featureS of your projecr so that i could add them in README.

**Comment by IIvexII** [comment]
This project is about providing APIs for LGU's timetable which return data in JSON format. There is an API `gc-integration` which automatically creates events on your google calendar so that it notifies you for the next class via google calendar.

**Comment by IIvexII** [comment]
Basic level of documentation is ready, so the purpose of this issue it fulfilled, So, I am closing this issue for now.
